title: "RESys Lab"
tagline: "Reconfigurable & Embedded Systems Laboratory"
description: "Reconfigurable & Embedded Systems Laboratory"
theme: jekyll-theme-cayman
logo: /images/logo.png
plugins:
  - jemoji
